import 'dart:collection';

const Map<String, String> kArabicStrings = UnmodifiableMapView<String, String>({
  'Home': 'الرئيسية',
  'Prayer': 'الصلاة',
  'Quran': 'القرآن',
  'Hadith': 'الحديث',
  'Tools': 'الأدوات',
  'More': 'المزيد',
  'Refresh': 'تحديث',
  'Refresh prayer times': 'تحديث أوقات الصلاة',
  'Try Again': 'حاول مرة أخرى',
  'Cancel': 'إلغاء',
  'Save': 'حفظ',
  'Close': 'إغلاق',
  'Done': 'تم',
  'Search': 'بحث',
  'Settings': 'الإعدادات',
  'Current Prayer': 'الصلاة الحالية',
  'Next Prayer': 'الصلاة التالية',
  'Prayer Time': 'وقت الصلاة',
  'Today': 'اليوم',
  'Sunrise': 'الشروق',
  'Sunset': 'الغروب',
  'Current Location': 'الموقع الحالي',
  'Today’s Prayer': 'صلاة اليوم',
  'Complete prayer schedule': 'جدول الصلاة الكامل',
  'Prayer Times': 'أوقات الصلاة',
  'Previous Prayer': 'الصلاة السابقة',
  'Current': 'الحالي',
  'Next': 'التالي',
  'Completed': 'تمت',
  'No prayer window': 'لا يوجد وقت للصلاة',
  'Start': 'البداية',
  'End': 'النهاية',
  'Jama’ah': 'الجماعة',
  'Friday': 'الجمعة',
  'Important Times Today': 'الأوقات المهمة اليوم',
  'Solar Noon': 'الزوال',
  'Makruh Time': 'وقت الكراهة',
  'Prohibited Time': 'الوقت المنهي عنه',
  'Nafl & Other Prayers': 'النوافل والصلوات الأخرى',
  'Important times for optional worship': 'أوقات مهمة للعبادات النافلة',
  'Ishraq': 'الإشراق',
  'Duha': 'الضحى',
  'Awwabin': 'الأوابين',
  'Tahajjud': 'التهجد',
  'Prayer Tracker': 'متابعة الصلوات',
  'Mark the prayers you have performed': 'حدد الصلوات التي أديتها',
  'Could not load prayer information': 'تعذر تحميل معلومات الصلاة',
  'Prayer times may vary depending on location, date, and calculation method.': 'قد تختلف أوقات الصلاة حسب الموقع والتاريخ وطريقة الحساب.',
  'Fajr': 'الفجر',
  'Dhuhr': 'الظهر',
  'Asr': 'العصر',
  'Maghrib': 'المغرب',
  'Isha': 'العشاء',
  'Jumu’ah': 'الجمعة',
  'Qibla': 'القبلة',
  'Tasbih': 'التسبيح',
  'Asma ul Husna': 'أسماء الله الحسنى',
  'Ruqyah': 'الرقية',
  'Zakat Calculator': 'حاسبة الزكاة',
  'Islamic Calendar': 'التقويم الإسلامي',
  'Nearby Mosque': 'المسجد القريب',
  'Islamic Books': 'الكتب الإسلامية',
  'Ayah of the Day': 'آية اليوم',
  'Hadith of the Day': 'حديث اليوم',
  'Dua of the Day': 'دعاء اليوم',
  'Continue Reading': 'متابعة القراءة',
  'Last Read': 'آخر قراءة',
  'See All': 'عرض الكل',
  'Language': 'اللغة',
  'Theme': 'المظهر',
  'Light': 'فاتح',
  'Dark': 'داكن',
  'System': 'النظام',
  'Bangla': 'البنغالية',
  'English': 'الإنجليزية',
  'Arabic': 'العربية',
  'Location unavailable': 'الموقع غير متاح',
  'No data available': 'لا توجد بيانات',
  'Something went wrong': 'حدث خطأ ما',
  'Loading...': 'جارٍ التحميل...',
  'Islamic Tools': 'الأدوات الإسلامية',
  'Worship & Practice': 'العبادة والعمل',
  'Dua': 'الدعاء',
  'Dua and supplication': 'الدعاء والمناجاة',
  'Dhikr counting and practice': 'عدّ الذكر والعبادة',
  'Quran and authentic duas': 'القرآن والأدعية الصحيحة',
  '99 Names of Allah': 'أسماء الله الحسنى',
  'Quran & Hadith': 'القرآن والحديث',
  'Reading, audio and saved knowledge': 'القراءة والاستماع والمعرفة المحفوظة',
  'Audio Quran': 'القرآن الصوتي',
  'Listen to Quran recitation': 'استمع إلى تلاوة القرآن',
  'Saved Hadith': 'الأحاديث المحفوظة',
  'Your favorite hadith': 'أحاديثك المفضلة',
  'Islamic knowledge library': 'مكتبة المعرفة الإسلامية',
  'Time & Direction': 'الوقت والاتجاه',
  'Islamic time, date and Qibla': 'الوقت والتاريخ والقبلة',
  'Find the direction of the Kaaba': 'تحديد اتجاه الكعبة',
  'Calendar': 'التقويم',
  'Hijri and Islamic dates': 'التواريخ الهجرية والإسلامية',
  'Islamic Calculations': 'الحسابات الإسلامية',
  'Calculate your Zakat': 'احسب زكاتك',
  'Your Islamic Tools': 'أدواتك الإسلامية',
  'Al-Quran': 'القرآن الكريم',
  'Hifzi Quran': 'القرآن الحفظي',
  '15-line offline Hifzi Quran': 'قرآن حفظي من 15 سطرًا بدون إنترنت',
  'Onudhabon Quran': 'قرآن التدبر',
  'Translation • Tafsir': 'الترجمة • التفسير',
  'Translation': 'الترجمة',
  'Offline cache': 'التخزين المؤقت دون اتصال',
});
