import 'dart:async';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../controllers/prayer_controller.dart';

class PrayerSpecialTimesCard extends StatefulWidget {
  final String languageCode;
  final DateTime? prohibitedStart, prohibitedEnd, makruhStart, makruhEnd;
  const PrayerSpecialTimesCard({super.key, required this.languageCode, this.prohibitedStart, this.prohibitedEnd, this.makruhStart, this.makruhEnd});
  bool get compact => prohibitedStart != null || prohibitedEnd != null || makruhStart != null || makruhEnd != null;
  @override State<PrayerSpecialTimesCard> createState() => _PrayerSpecialTimesCardState();
}

class _PrayerSpecialTimesCardState extends State<PrayerSpecialTimesCard> {
  Timer? _timer; DateTime _now = DateTime.now();
  @override void initState(){super.initState();_timer=Timer.periodic(const Duration(seconds:1),(_){if(mounted)setState(()=>_now=DateTime.now());});}
  @override void dispose(){_timer?.cancel();super.dispose();}
  String _label(String bn,String en,String ar)=>widget.languageCode=='en'?en:widget.languageCode=='ar'?ar:bn;
  DateTime? _parse(String value){final m=RegExp(r'^(\d{1,2}):(\d{2})\s*(AM|PM)$',caseSensitive:false).firstMatch(value.trim());if(m==null)return null;var h=int.parse(m.group(1)!);final min=int.parse(m.group(2)!);final p=m.group(3)!.toUpperCase();if(p=='AM'&&h==12)h=0;if(p=='PM'&&h!=12)h+=12;return DateTime(_now.year,_now.month,_now.day,h,min);}
  String _time(DateTime v){final h=v.hour%12==0?12:v.hour%12;return'$h:${v.minute.toString().padLeft(2,'0')} ${v.hour>=12?'PM':'AM'}';}
  String _left(Duration d){final s=d.inSeconds.clamp(0,86400);final m=s~/60,sec=s%60;return'$m:${sec.toString().padLeft(2,'0')} ${_label('মিনিট বাকি','min left','دقيقة متبقية')}';}
  List<_Window> _windows(PrayerController c,{required bool prohibited}){final sunrise=_parse(c.sunriseTime),noon=_parse(c.solarNoonTime),sunset=_parse(c.sunsetTime);if(sunrise==null||noon==null||sunset==null)return const [];final ranges=prohibited?<List<DateTime>>[[sunrise,sunrise.add(const Duration(minutes:15))],[noon.subtract(const Duration(minutes:10)),noon],[sunset.subtract(const Duration(minutes:15)),sunset]]:<List<DateTime>>[[sunrise.subtract(const Duration(minutes:15)),sunrise.add(const Duration(minutes:15))],[noon.subtract(const Duration(minutes:10)),noon.add(const Duration(minutes:5))],[sunset.subtract(const Duration(minutes:15)),sunset.add(const Duration(minutes:15))]];return ranges.map((r){final active=!_now.isBefore(r[0])&&_now.isBefore(r[1]);final past=!_now.isBefore(r[1]);return _Window(r[0],r[1],active,past);}).toList();}
  String _name(int i)=>i==0?_label('সূর্যোদয়','Sunrise','الشروق'):i==1?_label('জাওয়াল','Zawal','الزوال'):_label('সূর্যাস্ত','Sunset','الغروب');
  String _status(_Window w,int i){final n=_name(i);if(w.active)return'$n — ${_label('এখন চলছে','active now','جاري الآن')} • ${_left(w.end.difference(_now))}';if(w.past)return'$n — ${_label('শেষ','ended','انتهى')} • ${_time(w.start)} – ${_time(w.end)}';return'$n — ${_label('পরবর্তী','next','التالي')} • ${_time(w.start)} – ${_time(w.end)}';}
  @override Widget build(BuildContext context){final c=context.watch<PrayerController>();return widget.compact?_buildCompact(context,c):_buildDetailed(context,c);}
  Widget _buildCompact(BuildContext context,PrayerController c){final sunrise=_parse(c.sunriseTime),noon=_parse(c.solarNoonTime),sunset=_parse(c.sunsetTime);final windows=<({DateTime start,DateTime end,String bn,String en,String ar})>[];if(sunrise!=null)windows.add((start:sunrise.subtract(const Duration(minutes:15)),end:sunrise.add(const Duration(minutes:15)),bn:'সূর্যোদয়ের সময়',en:'Sunrise restriction',ar:'وقت النهي عند الشروق'));if(noon!=null)windows.add((start:noon.subtract(const Duration(minutes:10)),end:noon.add(const Duration(minutes:5)),bn:'জাওয়ালের সময়',en:'Zawal restriction',ar:'وقت النهي عند الزوال'));if(sunset!=null)windows.add((start:sunset.subtract(const Duration(minutes:15)),end:sunset.add(const Duration(minutes:15)),bn:'সূর্যাস্তের সময়',en:'Sunset restriction',ar:'وقت النهي عند الغروب'));final active=windows.where((w)=>!_now.isBefore(w.start)&&_now.isBefore(w.end)).toList();final next=windows.where((w)=>_now.isBefore(w.start)).toList();final w=active.isNotEmpty?active.first:(next.isNotEmpty?next.first:null);if(w==null)return const SizedBox.shrink();final color=Theme.of(context).colorScheme.error,fg=Theme.of(context).colorScheme.onSurface;final title=_label(w.bn,w.en,w.ar);final message=active.isNotEmpty?'$title — ${_label('এখন নামাজের নিষিদ্ধ/মাকরূহ সময় চলছে','Restricted prayer time is active','وقت النهي قائم الآن')} • ${_left(w.end.difference(_now))}':'$title — ${_label('আর','in','في')} ${_left(w.start.difference(_now))} ${_label('পর শুরু হবে','until it starts','حتى يبدأ')}';return Container(width:double.infinity,padding:const EdgeInsets.symmetric(horizontal:13,vertical:11),decoration:BoxDecoration(color:color.withValues(alpha:.08),borderRadius:BorderRadius.circular(16),border:Border.all(color:color.withValues(alpha:.25))),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(Icons.warning_amber_rounded,color:color,size:23),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(_label('সতর্কতা','Prayer Time Warning','تنبيه وقت الصلاة'),style:TextStyle(fontSize:13,fontWeight:FontWeight.w800,color:color)),const SizedBox(height:3),Text(message,style:TextStyle(fontSize:13.5,fontWeight:FontWeight.w700,color:fg))]))]);}
  Widget _buildDetailed(BuildContext context,PrayerController c){final t=Theme.of(context),p=t.colorScheme.primary,fg=t.colorScheme.onSurface,sec=t.textTheme.bodySmall?.color??fg.withValues(alpha:.7);final prohibited=_windows(c,prohibited:true),makruh=_windows(c,prohibited:false);final active=prohibited.any((w)=>w.active)||makruh.any((w)=>w.active);return Container(width:double.infinity,padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:t.cardColor,borderRadius:BorderRadius.circular(18),border:Border.all(color:p.withValues(alpha:.12))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Icon(active?Icons.block_rounded:Icons.warning_amber_rounded,size:21,color:p),const SizedBox(width:8),Expanded(child:Text(_label('মাকরূহ ও নিষিদ্ধ সময়','Makruh & Prohibited Times','أوقات الكراهة والنهي'),style:TextStyle(fontSize:16,fontWeight:FontWeight.w800,color:fg)))]),const SizedBox(height:12),_section(_label('নিষিদ্ধ সময়','Prohibited Times','أوقات النهي'),prohibited,p,sec,fg),const SizedBox(height:12),_section(_label('মাকরূহ সময়','Makruh Times','أوقات الكراهة'),makruh,p,sec,fg),const SizedBox(height:5),Text(_label('সময়গুলো প্রতি সেকেন্ডে লাইভ আপডেট হচ্ছে।','Times update live every second.','الأوقات تتحدث مباشرة كل ثانية.'),style:TextStyle(fontSize:11.5,color:sec))]));}
  Widget _section(String heading,List<_Window> windows,Color p,Color sec,Color fg)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(heading,style:TextStyle(fontSize:14,fontWeight:FontWeight.w800,color:fg)),const SizedBox(height:7),...List.generate(windows.length,(i)=>Padding(padding:EdgeInsets.only(bottom:i==windows.length-1?0:6),child:_item(_status(windows[i],i),windows[i].active,p,sec,fg)))]);
  Widget _item(String value,bool active,Color p,Color sec,Color fg)=>Container(width:double.infinity,padding:const EdgeInsets.symmetric(horizontal:10,vertical:8),decoration:BoxDecoration(color:p.withValues(alpha:active?.10:.045),borderRadius:BorderRadius.circular(12),border:active?Border.all(color:p.withValues(alpha:.22)):null),child:Row(children:[Icon(active?Icons.timer_rounded:Icons.schedule_rounded,size:18,color:p),const SizedBox(width:8),Expanded(child:Text(value,maxLines:2,overflow:TextOverflow.ellipsis,style:TextStyle(fontSize:13,color:fg,fontWeight:FontWeight.w700)))]));
}
class _Window{final DateTime start,end;final bool active,past;const _Window(this.start,this.end,this.active,this.past);}
