// GENERATED FILE. DO NOT EDIT BY HAND.
// Source: HsnSaboor/hadith-api-toon multilingual section metadata.

class GeneratedHadithChapterMetadata {
  const GeneratedHadithChapterMetadata._();

  static const Map<String, Map<int, GeneratedHadithChapterTitle>> books = {
    'bukhari': {
      0: GeneratedHadithChapterTitle(ar: "غير مصنف", bn: "অশ্রেণীবদ্ধ", en: "Uncategorized"),
      1: GeneratedHadithChapterTitle(ar: "الوحي", bn: "ওহী", en: "Revelation"),
      2: GeneratedHadithChapterTitle(ar: "الإيمان", bn: "ঈমান", en: "Belief"),
      3: GeneratedHadithChapterTitle(ar: "العلم", bn: "জ্ঞান", en: "Knowledge"),
      4: GeneratedHadithChapterTitle(ar: "الوضوء", bn: "ওজু", en: "Ablutions (Wudu')"),
      5: GeneratedHadithChapterTitle(ar: "الغسل", bn: "গোসল", en: "Bathing (Ghusl)"),
      6: GeneratedHadithChapterTitle(ar: "الحيض", bn: "হায়েজ", en: "Menstrual Periods"),
      7: GeneratedHadithChapterTitle(ar: "التيمم", bn: "তায়াম্মুম", en: "Rubbing hands and feet with dust (Tayammum)"),
      8: GeneratedHadithChapterTitle(ar: "الصلاة", bn: "নামাজ", en: "Prayers (Salat)"),
      9: GeneratedHadithChapterTitle(ar: "مواقيت الصلاة", bn: "নামাজের সময়", en: "Times of the Prayers"),
      10: GeneratedHadithChapterTitle(ar: "الأذان", bn: "আজান", en: "Call to Prayers (Adhaan)"),
      11: GeneratedHadithChapterTitle(ar: "صلاة الجمعة", bn: "জুমার নামাজ", en: "Friday Prayer"),
      12: GeneratedHadithChapterTitle(ar: "صلاة الخوف", bn: "ভয়ের নামাজ", en: "Fear Prayer"),
      13: GeneratedHadithChapterTitle(ar: "العيدين", bn: "দুই ঈদ", en: "The Two Festivals (Eids)"),
      14: GeneratedHadithChapterTitle(ar: "الوتر", bn: "বিতরের নামাজ", en: "Witr Prayer"),
      15: GeneratedHadithChapterTitle(ar: "الاستسقاء", bn: "ইস্তিস্কা", en: "Invoking Allah for Rain (Istisqaa)"),
      16: GeneratedHadithChapterTitle(ar: "الكسوف والخسوف", bn: "গ্রহণ", en: "Eclipses"),
      17: GeneratedHadithChapterTitle(ar: "سجود القرآن", bn: "কুরআন তিলাওয়াতের সময় সিজদা", en: "Prostration During Recital of Qur'an"),
      18: GeneratedHadithChapterTitle(ar: "قصر الصلاة", bn: "নামাজ কসর", en: "Shortening the Prayers (At-Taqseer)"),
      19: GeneratedHadithChapterTitle(ar: "التهجد", bn: "তাহাজ্জুদ", en: "Prayer at Night (Tahajjud)"),
      20: GeneratedHadithChapterTitle(ar: "فضل الصلاة في مسجد مكة والمدينة", bn: "মক্কা ও মদীনার মসজিদে নামাজের ফজিলত", en: "Virtues of Prayer at Masjid Makkah and Madinah"),
      21: GeneratedHadithChapterTitle(ar: "الأعمال في الصلاة", bn: "নামাজের মধ্যে কাজ", en: "Actions while Praying"),
      22: GeneratedHadithChapterTitle(ar: "السهو في الصلاة", bn: "নামাজে ভুল", en: "Forgetfulness in Prayer"),
      23: GeneratedHadithChapterTitle(ar: "الجنائز", bn: "জানাজা", en: "Funerals (Al-Janaa'iz)"),
      24: GeneratedHadithChapterTitle(ar: "الزكاة", bn: "যাকাত", en: "Obligatory Charity Tax (Zakat)"),
      25: GeneratedHadithChapterTitle(ar: "الحج", bn: "হজ", en: "Hajj (Pilgrimage)"),
      26: GeneratedHadithChapterTitle(ar: "العمرة", bn: "উমরাহ", en: "`Umrah (Minor pilgrimage)"),
      27: GeneratedHadithChapterTitle(ar: "كتاب المحصر", bn: "হজ্জ সম্পূর্ণ করতে বাধাপ্রাপ্ত হাজীগণ", en: "Pilgrims Prevented from Completing the Pilgrimage"),
      28: GeneratedHadithChapterTitle(ar: "الجنايات", bn: "হজের সময় শিকারের জরিমানা", en: "Penalty of Hunting while on Pilgrimage"),
      29: GeneratedHadithChapterTitle(ar: "فضل المدينة", bn: "মদীনার ফজিলত", en: "Virtues of Madinah"),
      30: GeneratedHadithChapterTitle(ar: "الصيام", bn: "রোজা", en: "Fasting"),
      31: GeneratedHadithChapterTitle(ar: "التراويح", bn: "তারাবীহ", en: "Praying at Night in Ramadaan (Taraweeh)"),
      32: GeneratedHadithChapterTitle(ar: "فضل ليلة القدر", bn: "কদর রাতের ফজিলত", en: "Virtues of the Night of Qadr"),
      33: GeneratedHadithChapterTitle(ar: "الاعتكاف", bn: "ইতিকাফ", en: "Retiring to a Mosque for Remembrance of Allah (I'tikaf)"),
      34: GeneratedHadithChapterTitle(ar: "البيع والتجارة", bn: "ক্রয়-বিক্রয় ও বাণিজ্য", en: "Sales and Trade"),
      35: GeneratedHadithChapterTitle(ar: "السلم", bn: "সালাম বিক্রয়", en: "Sales in which a Price is paid for Goods to be Delivered Later (As-Salam)"),
      36: GeneratedHadithChapterTitle(ar: "الشفعة", bn: "শুফ'আ", en: "Shuf'a"),
      37: GeneratedHadithChapterTitle(ar: "الإجارة", bn: "ভাড়া", en: "Hiring"),
      38: GeneratedHadithChapterTitle(ar: "الحوالة", bn: "হাওয়ালা", en: "Transferance of a Debt from One Person to Another (Al-Hawaala)"),
      39: GeneratedHadithChapterTitle(ar: "الكفالة", bn: "কাফালা", en: "Kafalah"),
      40: GeneratedHadithChapterTitle(ar: "كتاب الوكالة", bn: "প্রতিনিধিত্ব, ক্ষমতা অর্পণ, প্রতিনিধির মাধ্যমে ব্যবসা", en: "Representation, Authorization, Business by Proxy"),
      41: GeneratedHadithChapterTitle(ar: "المزارعة", bn: "কৃষি", en: "Agriculture"),
      42: GeneratedHadithChapterTitle(ar: "المساقاة", bn: "পানি বণ্টন", en: "Distribution of Water"),
      43: GeneratedHadithChapterTitle(ar: "كتاب فى الاستقراض", bn: "ঋণ, ঋণ পরিশোধ, সম্পত্তি অবরুদ্ধকরণ, দেউলিয়াত্ব", en: "Loans, Payment of Loans, Freezing of Property, Bankruptcy"),
      44: GeneratedHadithChapterTitle(ar: "الخصومات", bn: "খুসুমাত", en: "Khusoomaat"),
      45: GeneratedHadithChapterTitle(ar: "اللقطة", bn: "পাওয়া গেলে (লুকাতাহ)", en: "Lost Things Picked up by Someone (Luqatah)"),
      46: GeneratedHadithChapterTitle(ar: "المظالم", bn: "জুলুম", en: "Oppressions"),
      47: GeneratedHadithChapterTitle(ar: "الشركة", bn: "অংশীদারি", en: "Partnership"),
      48: GeneratedHadithChapterTitle(ar: "الرهن", bn: "বন্ধক", en: "Mortgaging"),
      49: GeneratedHadithChapterTitle(ar: "العتق", bn: "দাস মুক্তি", en: "Manumission of Slaves"),
      50: GeneratedHadithChapterTitle(ar: "المكاتب", bn: "মুকাতাব", en: "Makaatib"),
      51: GeneratedHadithChapterTitle(ar: "الهبة", bn: "উপহার", en: "Gifts"),
      52: GeneratedHadithChapterTitle(ar: "الشهادات", bn: "সাক্ষী", en: "Witnesses"),
      53: GeneratedHadithChapterTitle(ar: "الصلح", bn: "সন্ধি", en: "Peacemaking"),
      54: GeneratedHadithChapterTitle(ar: "الشروط", bn: "শর্তাবলী", en: "Conditions"),
      55: GeneratedHadithChapterTitle(ar: "الوصايا", bn: "ওসিয়ত", en: "Wills and Testaments (Wasaayaa)"),
      56: GeneratedHadithChapterTitle(ar: "الجهاد", bn: "জিহাদ", en: "Fighting for the Cause of Allah (Jihaad)"),
      57: GeneratedHadithChapterTitle(ar: "الخمس", bn: "খুমাস", en: "One-fifth of Booty to the Cause of Allah (Khumus)"),
      58: GeneratedHadithChapterTitle(ar: "الجزية والموادعة", bn: "জিজিয়া ও মুয়াহাদা", en: "Jizyah and Mawaada'ah"),
      59: GeneratedHadithChapterTitle(ar: "بدء الخلق", bn: "সৃষ্টির সূচনা", en: "Beginning of Creation"),
      60: GeneratedHadithChapterTitle(ar: "أنبياء", bn: "নবীগণ", en: "Prophets"),
      61: GeneratedHadithChapterTitle(ar: "فضائل النبي صلى الله عليه وسلم وأصحابه", bn: "নবী (সা.) ও তাঁর সাহাবীদের ফজিলত", en: "Virtues and Merits of the Prophet (pbuh) and his Companions"),
      62: GeneratedHadithChapterTitle(ar: "أصحاب النبي", bn: "নবীর সাহাবীরা", en: "Companions of the Prophet"),
      63: GeneratedHadithChapterTitle(ar: "فضل الأنصار", bn: "মদীনার সাহায্যকারীদের (আনসার) ফজিলত", en: "Merits of the Helpers in Madinah (Ansaar)"),
      64: GeneratedHadithChapterTitle(ar: "المغازي", bn: "নবী (সা.)-এর নেতৃত্বে সামরিক অভিযান (মাগাযী)", en: "Military Expeditions led by the Prophet (pbuh) (Al-Maghaazi)"),
      65: GeneratedHadithChapterTitle(ar: "تفسير القرآن", bn: "নবী (সা.)-এর কুরআন তাফসীর", en: "Prophetic Commentary on the Qur'an (Tafseer of the Prophet (pbuh))"),
      66: GeneratedHadithChapterTitle(ar: "فضل القرآن", bn: "কুরআনের ফজিলত", en: "Virtues of the Qur'an"),
      67: GeneratedHadithChapterTitle(ar: "كتاب النكاح", bn: "বিবাহ, নিকাহ", en: "Wedlock, Marriage (Nikaah)"),
      68: GeneratedHadithChapterTitle(ar: "الطلاق", bn: "তালাক", en: "Divorce"),
      69: GeneratedHadithChapterTitle(ar: "النفقة", bn: "পরিবারের ভরণপোষণ", en: "Supporting the Family"),
      70: GeneratedHadithChapterTitle(ar: "كتاب الأطعمة", bn: "খাদ্য, খাবার", en: "Food, Meals"),
      71: GeneratedHadithChapterTitle(ar: "العقيقة", bn: "আকীকা", en: "Sacrifice on Occasion of Birth (`Aqiqa)"),
      72: GeneratedHadithChapterTitle(ar: "كتاب الذبائح والصيد", bn: "শিকার, যবাহ (পশু জবেহ করা)", en: "Hunting, Slaughtering"),
      73: GeneratedHadithChapterTitle(ar: "الضحايا", bn: "কুরবানি", en: "Al-Adha Festival Sacrifice (Adaahi)"),
      74: GeneratedHadithChapterTitle(ar: "الأشربة", bn: "পানীয়", en: "Drinks"),
      75: GeneratedHadithChapterTitle(ar: "المرضى", bn: "রোগী", en: "Patients"),
      76: GeneratedHadithChapterTitle(ar: "الطب", bn: "চিকিৎসা", en: "Medicine"),
      77: GeneratedHadithChapterTitle(ar: "اللباس", bn: "পোশাক", en: "Dress"),
      78: GeneratedHadithChapterTitle(ar: "الأدب", bn: "সদাচার ও আদব", en: "Good Manners and Form (Al-Adab)"),
      79: GeneratedHadithChapterTitle(ar: "الاستئذان", bn: "অনুমতি চাওয়া", en: "Asking Permission"),
      80: GeneratedHadithChapterTitle(ar: "الدعوات", bn: "দোয়া", en: "Invocations"),
      81: GeneratedHadithChapterTitle(ar: "الرقاق", bn: "হৃদয় নরম করা (রিকাক)", en: "To make the Heart Tender (Ar-Riqaq)"),
      82: GeneratedHadithChapterTitle(ar: "القدر", bn: "তাকদীর", en: "Divine Will (Al-Qadar)"),
      83: GeneratedHadithChapterTitle(ar: "الأيمان والنذور", bn: "শপথ ও মানত", en: "Oaths and Vows"),
      84: GeneratedHadithChapterTitle(ar: "كفارات الأيمان", bn: "শপথ ভঙ্গের কাফফারা", en: "Expiation for Unfulfilled Oaths"),
      85: GeneratedHadithChapterTitle(ar: "الفرائض", bn: "উত্তরাধিকারের বিধি", en: "Laws of Inheritance (Al-Faraa'id)"),
      86: GeneratedHadithChapterTitle(ar: "الحدود", bn: "হদ", en: "Limits and Punishments set by Allah (Hudood)"),
      87: GeneratedHadithChapterTitle(ar: "الديات", bn: "দিয়াত", en: "Blood Money (Ad-Diyat)"),
      88: GeneratedHadithChapterTitle(ar: "الردة", bn: "মুরতাদ", en: "Apostates"),
      89: GeneratedHadithChapterTitle(ar: "الإكراه", bn: "বাধ্যতামূলক বিবৃতি", en: "(Statements made under) Coercion"),
      90: GeneratedHadithChapterTitle(ar: "الحيل", bn: "কৌশল", en: "Tricks"),
      91: GeneratedHadithChapterTitle(ar: "تعبير الرؤيا", bn: "স্বপ্নের ব্যাখ্যা", en: "Interpretation of Dreams"),
      92: GeneratedHadithChapterTitle(ar: "الفتن", bn: "ফিতনা ও কিয়ামত", en: "Afflictions and the End of the World"),
      93: GeneratedHadithChapterTitle(ar: "الأحكام", bn: "ফায়সালা", en: "Judgments (Ahkaam)"),
      94: GeneratedHadithChapterTitle(ar: "الرغبة", bn: "ইচ্ছা", en: "Wishes"),
      95: GeneratedHadithChapterTitle(ar: "الشهادات", bn: "সত্যবাদী ব্যক্তির তথ্য গ্রহণ", en: "Accepting Information Given by a Truthful Person"),
      96: GeneratedHadithChapterTitle(ar: "الاعتصام بالكتاب والسنة", bn: "কুরআন ও সুন্নাহের প্রতি দৃঢ় থাকা", en: "Holding Fast to the Qur'an and Sunnah"),
    },
    'muslim': {
      0: GeneratedHadithChapterTitle(ar: "غير مصنف", bn: "অশ্রেণীবদ্ধ", en: "Uncategorized"),
      1: GeneratedHadithChapterTitle(ar: "كتاب الإيمان", bn: "ঈমানের কিতাব", en: "The Book of Faith"),
      2: GeneratedHadithChapterTitle(ar: "كتاب الطهارة", bn: "পবিত্রতার কিতাব", en: "The Book of Purification"),
      3: GeneratedHadithChapterTitle(ar: "كتاب الحيض", bn: "হায়েজের কিতাব", en: "The Book of Menstruation"),
      4: GeneratedHadithChapterTitle(ar: "كتاب الصلاة", bn: "নামাজের কিতাব", en: "The Book of Prayers"),
      5: GeneratedHadithChapterTitle(ar: "كتاب المساجد ومواضع الصلاة", bn: "মসজিদ ও নামাজের স্থানের কিতাব", en: "The Book of Mosques and Places of Prayer"),
      6: GeneratedHadithChapterTitle(ar: "كتاب صلاة المسافرين", bn: "নামাজ - মুসাফিরদের কিতাব", en: "The Book of Prayer - Travellers"),
      7: GeneratedHadithChapterTitle(ar: "كتاب صلاة الجمعة", bn: "জুমার নামাজের কিতাব", en: "The Book of Prayer - Friday"),
      8: GeneratedHadithChapterTitle(ar: "كتاب صلاة العيدين", bn: "দুই ঈদের নামাজের কিতাব", en: "The Book of Prayer - Two Eids"),
      9: GeneratedHadithChapterTitle(ar: "كتاب صلاة الاستسقاء", bn: "বৃষ্টির নামাজের কিতাব", en: "The Book of Prayer - Rain"),
      10: GeneratedHadithChapterTitle(ar: "كتاب صلاة الكسوف", bn: "গ্রহণের নামাজের কিতাব", en: "The Book of Prayer - Eclipses"),
      11: GeneratedHadithChapterTitle(ar: "كتاب صلاة الجنائز", bn: "জানাজার নামাজের কিতাব", en: "The Book of Prayer - Funerals"),
      12: GeneratedHadithChapterTitle(ar: "كتاب الزكاة", bn: "যাকাতের কিতাব", en: "The Book of Zakat"),
      13: GeneratedHadithChapterTitle(ar: "كتاب الصيام", bn: "রোজার কিতাব", en: "The Book of Fasting"),
      14: GeneratedHadithChapterTitle(ar: "كتاب الاعتكاف", bn: "ইতিকাফের কিতাব", en: "The Book of I'tikaf"),
      15: GeneratedHadithChapterTitle(ar: "كتاب الحج", bn: "হজের কিতাব", en: "The Book of Pilgrimage"),
      16: GeneratedHadithChapterTitle(ar: "كتاب النكاح", bn: "বিবাহের কিতাব", en: "The Book of Marriage"),
      17: GeneratedHadithChapterTitle(ar: "كتاب الرضاع", bn: "দুধ পানের কিতাব", en: "The Book of Suckling"),
      18: GeneratedHadithChapterTitle(ar: "كتاب الطلاق", bn: "তালাকের কিতাব", en: "The Book of Divorce"),
      19: GeneratedHadithChapterTitle(ar: "كتاب اللعان", bn: "লানতের কিতাব", en: "The Book of Invoking Curses"),
      20: GeneratedHadithChapterTitle(ar: "كتاب العتق", bn: "দাস মুক্তির কিতাব", en: "The Book of Emancipating Slaves"),
      21: GeneratedHadithChapterTitle(ar: "كتاب البيوع", bn: "লেনদেনের কিতাব", en: "The Book of Transactions"),
      22: GeneratedHadithChapterTitle(ar: "كتاب المساقاة", bn: "মুসাকার কিতাব", en: "The Book of Musaqah"),
      23: GeneratedHadithChapterTitle(ar: "كتاب الفرائض", bn: "উত্তরাধিকারের নিয়মের কিতাব", en: "The Book of the Rules of Inheritance"),
      24: GeneratedHadithChapterTitle(ar: "كتاب الهبة", bn: "উপহারের কিতাব", en: "The Book of Gifts"),
      25: GeneratedHadithChapterTitle(ar: "كتاب الوصية", bn: "ওসিয়তের কিতাব", en: "The Book of Wills"),
      26: GeneratedHadithChapterTitle(ar: "كتاب النذر", bn: "মানতের কিতাব", en: "The Book of Vows"),
      27: GeneratedHadithChapterTitle(ar: "كتاب الأيمان", bn: "শপথের কিতাব", en: "The Book of Oaths"),
      28: GeneratedHadithChapterTitle(ar: "كتاب القسم والمحاربين والقصاص والديات", bn: "শপথ, মুহারিবিন, কিসাস ও দিয়াতের কিতাব", en: "The Book of Oaths, Muharibin, Qasas (Retaliation), and Diyat (Blood Money)"),
      29: GeneratedHadithChapterTitle(ar: "كتاب الحدود", bn: "হদের কিতাব", en: "The Book of Legal Punishments"),
      30: GeneratedHadithChapterTitle(ar: "كتاب القضاء", bn: "বিচারের কিতাব", en: "The Book of Judicial Decisions"),
      31: GeneratedHadithChapterTitle(ar: "كتاب اللقطة", bn: "হারানো জিনিসের কিতাব", en: "The Book of Lost Property"),
      32: GeneratedHadithChapterTitle(ar: "كتاب الجهاد والسير", bn: "জিহাদ ও অভিযানের কিতাব", en: "The Book of Jihad and Expeditions"),
      33: GeneratedHadithChapterTitle(ar: "كتاب الإمارة", bn: "সরকারের কিতাব", en: "The Book on Government"),
      34: GeneratedHadithChapterTitle(ar: "كتاب الصيد والذبائح وما يؤكل", bn: "শিকার, জবাই ও খাদ্যের কিতাব", en: "The Book of Hunting, Slaughter, and what may be Eaten"),
      35: GeneratedHadithChapterTitle(ar: "كتاب الضحايا", bn: "কুরবানির কিতাব", en: "The Book of Sacrifices"),
      36: GeneratedHadithChapterTitle(ar: "كتاب الأشربة", bn: "পানীয়ের কিতাব", en: "The Book of Drinks"),
      37: GeneratedHadithChapterTitle(ar: "كتاب اللباس والزينة", bn: "পোশাক ও অলংকারের কিতাব", en: "The Book of Clothes and Adornment"),
      38: GeneratedHadithChapterTitle(ar: "كتاب الآداب", bn: "আদব ও শিষ্টাচারের কিতাব", en: "The Book of Manners and Etiquette"),
      39: GeneratedHadithChapterTitle(ar: "كتاب السلام", bn: "অভিবাদনের কিতাব", en: "The Book of Greetings"),
      40: GeneratedHadithChapterTitle(ar: "كتاب الألفاظ من الأدب وغيرها", bn: "সঠিক শব্দ ব্যবহারের কিতাব", en: "The Book Concerning the Use of Correct Words"),
      41: GeneratedHadithChapterTitle(ar: "كتاب الشعر", bn: "কবিতার কিতাব", en: "The Book of Poetry"),
      42: GeneratedHadithChapterTitle(ar: "كتاب الرؤيا", bn: "স্বপ্নের কিতাব", en: "The Book of Dreams"),
      43: GeneratedHadithChapterTitle(ar: "كتاب الفضائل", bn: "ফজিলতের কিতাব", en: "The Book of Virtues"),
      44: GeneratedHadithChapterTitle(ar: "كتاب فضائل الصحابة", bn: "সাহাবীদের ফজিলতের কিতাব", en: "The Book of the Merits of the Companions"),
      45: GeneratedHadithChapterTitle(ar: "كتاب البر والصلة والآداب", bn: "ফজিলত, সদাচার ও আত্মীয়তার সম্পর্কের কিতাব", en: "The Book of Virtue, Enjoining Good Manners, and Joining of the Ties of Kinship"),
      46: GeneratedHadithChapterTitle(ar: "كتاب القدر", bn: "তাকদীরের কিতাব", en: "The Book of Destiny"),
      47: GeneratedHadithChapterTitle(ar: "كتاب العلم", bn: "জ্ঞানের কিতাব", en: "The Book of Knowledge"),
      48: GeneratedHadithChapterTitle(ar: "كتاب الذكر والدعاء والتوبة والاستغفار", bn: "আল্লাহর স্মরণ, দোয়া, তাওবা ও ক্ষমা প্রার্থনার কিতাব", en: "The Book Pertaining to the Remembrance of Allah, Supplication, Repentance and Seeking Forgiveness"),
      49: GeneratedHadithChapterTitle(ar: "كتاب الرقاق", bn: "হৃদয় গলানো বর্ণনার কিতাব", en: "The Book of Heart-Melting Traditions"),
      50: GeneratedHadithChapterTitle(ar: "كتاب التوبة", bn: "তাওবার কিতাব", en: "The Book of Repentance"),
      51: GeneratedHadithChapterTitle(ar: "كتاب صفات المنافقين وأحكامهم", bn: "মুনাফিকদের বৈশিষ্ট্য ও তাদের বিধানের কিতাব", en: "Characteristics of The Hypocrites And Rulings Concerning Them"),
      52: GeneratedHadithChapterTitle(ar: "كتاب الجنة والنار", bn: "কিয়ামত, জান্নাত ও জাহান্নামের কিতাব", en: "Characteristics of the Day of Judgment, Paradise, and Hell"),
      53: GeneratedHadithChapterTitle(ar: "كتاب وصف الجنة", bn: "জান্নাত, তার বর্ণনা, নেয়ামত ও বাসিন্দাদের কিতাব", en: "The Book of Paradise, its Description, its Bounties and its Inhabitants"),
      54: GeneratedHadithChapterTitle(ar: "كتاب الفتن وأشراط الساعة", bn: "ফিতনা ও কিয়ামতের লক্ষণের কিতাব", en: "The Book of Tribulations and Portents of the Last Hour"),
      55: GeneratedHadithChapterTitle(ar: "كتاب الزهد والرقائق", bn: "জুহদ ও হৃদয় নরম করার কিতাব", en: "The Book of Zuhd and Softening of Hearts"),
      56: GeneratedHadithChapterTitle(ar: "كتاب التفسير", bn: "কুরআনের তাফসীরের কিতাব", en: "The Book of Commentary on the Qur'an"),
    },
    'abudawud': {
      1: GeneratedHadithChapterTitle(ar: "كتاب الطهارة", bn: "পবিত্রতা (কিতাব আত-তাহারাহ)", en: "Purification (Kitab Al-Taharah)"),
      2: GeneratedHadithChapterTitle(ar: "كتاب الصلاة", bn: "নামাজ (কিতাব আস-সালাত)", en: "Prayer (Kitab Al-Salat)"),
      3: GeneratedHadithChapterTitle(ar: "كتاب الاستسقاء", bn: "বৃষ্টির নামাজ (কিতাব আল-ইস্তিসকা)", en: "The Book Of The Prayer For Rain (Kitab al-Istisqa')"),
      4: GeneratedHadithChapterTitle(ar: "كتاب صلاة المسافرين", bn: "নামাজ: সফরে নামাজের বিস্তারিত বিধি", en: "Prayer (Kitab Al-Salat): Detailed Rules of Law about the Prayer during Journey"),
      5: GeneratedHadithChapterTitle(ar: "كتاب التطوع", bn: "নামাজ: নফল নামাজ", en: "Prayer (Kitab Al-Salat): Voluntary Prayers"),
      6: GeneratedHadithChapterTitle(ar: "كتاب صلاة رمضان", bn: "নামাজ: রমজান সম্পর্কিত বিস্তারিত নির্দেশ", en: "Prayer (Kitab Al-Salat): Detailed Injunctions about Ramadan"),
      7: GeneratedHadithChapterTitle(ar: "كتاب سجود القرآن", bn: "নামাজ: কুরআন তিলাওয়াতের সময় সিজদা", en: "Prayer (Kitab Al-Salat): Prostration while reciting the Qur'an"),
      8: GeneratedHadithChapterTitle(ar: "كتاب الوتر", bn: "নামাজ: বিতর সম্পর্কিত বিস্তারিত নির্দেশ", en: "Prayer (Kitab Al-Salat): Detailed Injunctions about Witr"),
      9: GeneratedHadithChapterTitle(ar: "كتاب الزكاة", bn: "যাকাত (কিতাব আয-যাকাত)", en: "Zakat (Kitab Al-Zakat)"),
      10: GeneratedHadithChapterTitle(ar: "كتاب اللقطة", bn: "হারানো ও পাওয়া জিনিসের কিতাব", en: "The Book of Lost and Found Items"),
      11: GeneratedHadithChapterTitle(ar: "كتاب المناسك", bn: "হজের আনুষ্ঠানিকতা (কিতাব আল-মানাসিক ওয়াল-হজ)", en: "The Rites of Hajj (Kitab Al-Manasik Wa'l-Hajj)"),
      12: GeneratedHadithChapterTitle(ar: "كتاب النكاح", bn: "বিবাহ (কিতাব আন-নিকাহ)", en: "Marriage (Kitab Al-Nikah)"),
      13: GeneratedHadithChapterTitle(ar: "كتاب الطلاق", bn: "তালাক (কিতাব আত-তালাক)", en: "Divorce (Kitab Al-Talaq)"),
      14: GeneratedHadithChapterTitle(ar: "كتاب الصيام", bn: "রোজা (কিতাব আস-সিয়াম)", en: "Fasting (Kitab Al-Siyam)"),
      15: GeneratedHadithChapterTitle(ar: "كتاب الجهاد", bn: "জিহাদ (কিতাব আল-জিহাদ)", en: "Jihad (Kitab Al-Jihad)"),
      16: GeneratedHadithChapterTitle(ar: "كتاب الضحايا", bn: "কুরবানি (কিতাব আদ-দাহায়া)", en: "Sacrifice (Kitab Al-Dahaya)"),
      17: GeneratedHadithChapterTitle(ar: "كتاب الصيد", bn: "শিকার (কিতাব আস-সাইদ)", en: "Game (Kitab Al-Said)"),
      18: GeneratedHadithChapterTitle(ar: "كتاب الوصايا", bn: "ওসিয়ত (কিতাব আল-ওয়াসায়া)", en: "Wills (Kitab Al-Wasaya)"),
      19: GeneratedHadithChapterTitle(ar: "كتاب الفرائض", bn: "উত্তরাধিকারের অংশ (কিতাব আল-ফারায়িদ)", en: "Shares of Inheritance (Kitab Al-Fara'id)"),
      20: GeneratedHadithChapterTitle(ar: "كتاب الخراج والإمارة", bn: "খরাজ, গনীমত ও শাসন (কিতাব আল-খারাজ, ওয়াল-ফাই' ওয়াল-ইমারাহ)", en: "Tribute, Spoils, and Rulership (Kitab Al-Kharaj, Wal-Fai' Wal-Imarah)"),
      21: GeneratedHadithChapterTitle(ar: "كتاب الجنائز", bn: "জানাজা (কিতাব আল-জানায়িজ)", en: "Funerals (Kitab Al-Jana'iz)"),
      22: GeneratedHadithChapterTitle(ar: "كتاب الأيمان والنذور", bn: "শপথ ও মানত (কিতাব আল-আইমান ওয়াল-নুধুর)", en: "Oaths and Vows (Kitab Al-Aiman Wa Al-Nudhur)"),
      23: GeneratedHadithChapterTitle(ar: "كتاب البيوع", bn: "বাণিজ্যিক লেনদেন (কিতাব আল-বুইউ)", en: "Commercial Transactions (Kitab Al-Buyu)"),
      24: GeneratedHadithChapterTitle(ar: "كتاب الإجارة", bn: "মজুরি (কিতাব আল-ইজারাহ)", en: "Wages (Kitab Al-Ijarah)"),
      25: GeneratedHadithChapterTitle(ar: "كتاب الأقضية", bn: "বিচারকের কার্যালয় (কিতাব আল-আকদিয়াহ)", en: "The Office of the Judge (Kitab Al-Aqdiyah)"),
      26: GeneratedHadithChapterTitle(ar: "كتاب العلم", bn: "জ্ঞান (কিতাব আল-ইলম)", en: "Knowledge (Kitab Al-Ilm)"),
      27: GeneratedHadithChapterTitle(ar: "كتاب الأشربة", bn: "পানীয় (কিতাব আল-আশরিবাহ)", en: "Drinks (Kitab Al-Ashribah)"),
      28: GeneratedHadithChapterTitle(ar: "كتاب الأطعمة", bn: "খাদ্য (কিতাব আল-আতআইমাহ)", en: "Foods (Kitab Al-At'imah)"),
      29: GeneratedHadithChapterTitle(ar: "كتاب الطب", bn: "চিকিৎসা (কিতাব আত-তিব্ব)", en: "Medicine (Kitab Al-Tibb)"),
      30: GeneratedHadithChapterTitle(ar: "كتاب الكهانة والتطير", bn: "ভবিষ্যদ্বাণী ও অশুভ লক্ষণ (কিতাব আল-কাহানাহ ওয়া তাতাইয়্যুর)", en: "Divination and Omens (Kitab Al-Kahanah Wa Al-Tatayyur)"),
      31: GeneratedHadithChapterTitle(ar: "كتاب العتق", bn: "দাস মুক্তির কিতাব", en: "The Book of Manumission of Slaves"),
      32: GeneratedHadithChapterTitle(ar: "كتاب الحروف والقراءات", bn: "কুরআনের উপভাষা ও কিরাআত (কিতাব আল-হুরুফ ওয়াল-কিরাআত)", en: "Dialects and Readings of the Qur'an (Kitab Al-Huruf Wa Al-Qira'at)"),
      33: GeneratedHadithChapterTitle(ar: "كتاب الحمام", bn: "গরম গোসলখানা (কিতাব আল-হাম্মাম)", en: "Hot Baths (Kitab Al-Hammam)"),
      34: GeneratedHadithChapterTitle(ar: "كتاب اللباس", bn: "পোশাক (কিতাব আল-লিবাস)", en: "Clothing (Kitab Al-Libas)"),
      35: GeneratedHadithChapterTitle(ar: "كتاب الترجل", bn: "চুল আঁচড়ানো (কিতাব আত-তারাজ্জুল)", en: "Combing the Hair (Kitab Al-Tarajjul)"),
      36: GeneratedHadithChapterTitle(ar: "كتاب الخاتم", bn: "মোহরের আংটি (কিতাব আল-খাতাম)", en: "Signet-Rings (Kitab Al-Khatam)"),
      37: GeneratedHadithChapterTitle(ar: "كتاب الفتن والملاحم", bn: "ফিতনা ও ভয়ঙ্কর যুদ্ধ (কিতাব আল-ফিতান ওয়াল-মালাহিম)", en: "Trials and Fierce Battles (Kitab Al-Fitan Wa Al-Malahim)"),
      38: GeneratedHadithChapterTitle(ar: "كتاب المهدي", bn: "প্রতিশ্রুত মুক্তিদাতা (কিতাব আল-মাহদি)", en: "The Promised Deliverer (Kitab Al-Mahdi)"),
      39: GeneratedHadithChapterTitle(ar: "كتاب الملاحم", bn: "যুদ্ধ (কিতাব আল-মালাহিম)", en: "Battles (Kitab Al-Malahim)"),
      40: GeneratedHadithChapterTitle(ar: "كتاب الحدود", bn: "নির্ধারিত শাস্তি (কিতাব আল-হুদুদ)", en: "Prescribed Punishments (Kitab Al-Hudud)"),
      41: GeneratedHadithChapterTitle(ar: "كتاب الديات", bn: "দিয়াতের প্রকার (কিতাব আদ-দিয়াত)", en: "Types of Blood-Wit (Kitab Al-Diyat)"),
      42: GeneratedHadithChapterTitle(ar: "كتاب السنة", bn: "নবীর আদর্শ আচরণ (কিতাব আস-সুন্নাহ)", en: "Model Behavior of the Prophet (Kitab Al-Sunnah)"),
      43: GeneratedHadithChapterTitle(ar: "كتاب الأدب", bn: "সাধারণ আচরণ (কিতাব আল-আদাব)", en: "General Behavior (Kitab Al-Adab)"),
    },
    'tirmidhi': {
      1: GeneratedHadithChapterTitle(ar: "كتاب الطهارة", bn: "পবিত্রতার কিতাব", en: "The Book on Purification"),
      2: GeneratedHadithChapterTitle(ar: "كتاب الصلاة", bn: "নামাজের কিতাব", en: "The Book on Salat (Prayer)"),
      3: GeneratedHadithChapterTitle(ar: "كتاب الوتر", bn: "বিতরের কিতাব", en: "The Book on Al-Witr"),
      4: GeneratedHadithChapterTitle(ar: "كتاب يوم الجمعة", bn: "জুমার দিনের কিতাব", en: "The Book on the Day of Friday"),
      5: GeneratedHadithChapterTitle(ar: "كتاب العيدين", bn: "দুই ঈদের কিতাব", en: "The Book on the Two Eids"),
      6: GeneratedHadithChapterTitle(ar: "كتاب السفر", bn: "সফরের কিতাব", en: "The Book on Traveling"),
      7: GeneratedHadithChapterTitle(ar: "كتاب الزكاة", bn: "যাকাতের কিতাব", en: "The Book on Zakat"),
      8: GeneratedHadithChapterTitle(ar: "كتاب الصيام", bn: "রোজার কিতাব", en: "The Book on Fasting"),
      9: GeneratedHadithChapterTitle(ar: "كتاب الحج", bn: "হজের কিতাব", en: "The Book on Hajj"),
      10: GeneratedHadithChapterTitle(ar: "كتاب الجنائز", bn: "জানাজার কিতাব", en: "The Book on Jana''iz (Funerals)"),
      11: GeneratedHadithChapterTitle(ar: "كتاب النكاح", bn: "বিবাহের কিতাব", en: "The Book on Marriage"),
      12: GeneratedHadithChapterTitle(ar: "كتاب الرضاع", bn: "দুধ পানের কিতাব", en: "The Book on Suckling"),
      13: GeneratedHadithChapterTitle(ar: "كتاب الطلاق واللعان", bn: "তালাক ও লিয়ানের কিতাব", en: "The Book on Divorce and Li'an"),
      14: GeneratedHadithChapterTitle(ar: "كتاب البيوع", bn: "ব্যবসার কিতাব", en: "The Book on Business"),
      15: GeneratedHadithChapterTitle(ar: "أحكام رسول الله", bn: "রাসূলুল্লাহর বিচার সংক্রান্ত অধ্যায়", en: "The Chapters On Judgements From The Messenger of Allah"),
      16: GeneratedHadithChapterTitle(ar: "كتاب الديات", bn: "দিয়াতের কিতাব", en: "The Book on Blood Money"),
      17: GeneratedHadithChapterTitle(ar: "كتاب الحدود", bn: "হদের কিতাব", en: "The Book on Legal Punishments (Al-Hudud)"),
      18: GeneratedHadithChapterTitle(ar: "كتاب الصيد", bn: "শিকারের কিতাব", en: "The Book on Hunting"),
      19: GeneratedHadithChapterTitle(ar: "كتاب الأضاحي", bn: "কুরবানির কিতাব", en: "The Book on Sacrifices"),
      20: GeneratedHadithChapterTitle(ar: "كتاب الأيمان والنذور", bn: "মানত ও শপথের কিতাব", en: "The Book on Vows and Oaths"),
      21: GeneratedHadithChapterTitle(ar: "كتاب السير", bn: "সামরিক অভিযানের কিতাব", en: "The Book on Military Expeditions"),
      22: GeneratedHadithChapterTitle(ar: "كتاب فضائل الجهاد", bn: "জিহাদের ফজিলতের কিতাব", en: "The Book on Virtues of Jihad"),
      23: GeneratedHadithChapterTitle(ar: "كتاب الجهاد", bn: "জিহাদের কিতাব", en: "The Book on Jihad"),
      24: GeneratedHadithChapterTitle(ar: "كتاب اللباس", bn: "পোশাকের কিতাব", en: "The Book on Clothing"),
      25: GeneratedHadithChapterTitle(ar: "كتاب الأطعمة", bn: "খাদ্যের কিতাব", en: "The Book on Food"),
      26: GeneratedHadithChapterTitle(ar: "كتاب الأشربة", bn: "পানীয়ের কিতাব", en: "The Book on Drinks"),
      27: GeneratedHadithChapterTitle(ar: "كتاب البر والصلة", bn: "ধার্মিকতা ও আত্মীয়তার সম্পর্ক রক্ষার অধ্যায়", en: "Chapters on Righteousness And Maintaining Good Relations With Relatives"),
      28: GeneratedHadithChapterTitle(ar: "كتاب الطب", bn: "চিকিৎসার অধ্যায়", en: "Chapters on Medicine"),
      29: GeneratedHadithChapterTitle(ar: "كتاب الفرائض", bn: "উত্তরাধিকারের অধ্যায়", en: "Chapters On Inheritance"),
      30: GeneratedHadithChapterTitle(ar: "كتاب الوصايا", bn: "ওসিয়তের অধ্যায়", en: "Chapters On Wasaya (Wills and Testament)"),
      31: GeneratedHadithChapterTitle(ar: "كتاب الولاء والهبة", bn: "ওয়ালা ও উপহারের অধ্যায়", en: "Chapters On Wala' And Gifts"),
      32: GeneratedHadithChapterTitle(ar: "كتاب القدر", bn: "তাকদীরের অধ্যায়", en: "Chapters On Al-Qadar"),
      35: GeneratedHadithChapterTitle(ar: "كتاب الشهادات", bn: "সাক্ষীদের অধ্যায়", en: "Chapters On Witnesses"),
      36: GeneratedHadithChapterTitle(ar: "كتاب الزهد", bn: "জুহদের অধ্যায়", en: "Chapters On Zuhd"),
      37: GeneratedHadithChapterTitle(ar: "كتاب صفة القيامة والرقائق والورع", bn: "কিয়ামতের বর্ণনা, আর-রিকাক ও আল-ওয়ারার অধ্যায়", en: "Chapters on the description of the Day of Judgement, Ar-Riqaq, and Al-Wara'"),
      38: GeneratedHadithChapterTitle(ar: "كتاب صفة الجنة", bn: "জান্নাতের বর্ণনার অধ্যায়", en: "Chapters on the description of Paradise"),
      39: GeneratedHadithChapterTitle(ar: "كتاب صفة النار", bn: "জাহান্নামের বর্ণনার কিতাব", en: "The Book on the Description of Hellfire"),
      43: GeneratedHadithChapterTitle(ar: "كتاب الأدب", bn: "আদবের অধ্যায়", en: "Chapters on Manners"),
      44: GeneratedHadithChapterTitle(ar: "كتاب الأمثال", bn: "উপমার অধ্যায়", en: "Chapters on Parables"),
      45: GeneratedHadithChapterTitle(ar: "كتاب فضائل القرآن", bn: "কুরআনের ফজিলতের অধ্যায়", en: "Chapters on The Virtues of the Qur'an"),
      46: GeneratedHadithChapterTitle(ar: "كتاب القراءات", bn: "তিলাওয়াতের অধ্যায়", en: "Chapters on Recitation"),
      47: GeneratedHadithChapterTitle(ar: "كتاب التفسير", bn: "তাফসীরের অধ্যায়", en: "Chapters on Tafsir"),
      49: GeneratedHadithChapterTitle(ar: "كتاب المناقب", bn: "ফজিলতের অধ্যায়", en: "Chapters on Virtues"),
    },
    'nasai': {
      0: GeneratedHadithChapterTitle(ar: "غير مصنف", bn: "অশ্রেণীবদ্ধ", en: "Uncategorized"),
      1: GeneratedHadithChapterTitle(ar: "كتاب الطهارة", bn: "পবিত্রতার কিতাব", en: "The Book of Purification"),
      2: GeneratedHadithChapterTitle(ar: "كتاب الماء", bn: "পানির কিতাব", en: "The Book of Water"),
      3: GeneratedHadithChapterTitle(ar: "كتاب الحيض والاستحاضة", bn: "হায়েজ ও ইস্তিহাদার কিতাব", en: "The Book of Menstruation and Istihadah"),
      4: GeneratedHadithChapterTitle(ar: "كتاب الغسل والتيمم", bn: "গোসল ও তায়াম্মুমের কিতাব", en: "The Book of Ghusl and Tayammum"),
      5: GeneratedHadithChapterTitle(ar: "كتاب الصلاة", bn: "নামাজের কিতাব", en: "The Book of Salah"),
      6: GeneratedHadithChapterTitle(ar: "كتاب المواقيت", bn: "নামাজের সময়ের কিতাব", en: "The Book of the Times (of Prayer)"),
      7: GeneratedHadithChapterTitle(ar: "كتاب الأذان", bn: "আজানের কিতাব", en: "The Book of the Adhan (The Call to Prayer)"),
      8: GeneratedHadithChapterTitle(ar: "كتاب المساجد", bn: "মসজিদের কিতাব", en: "The Book of the Masjids"),
      9: GeneratedHadithChapterTitle(ar: "كتاب القبلة", bn: "কিবলার কিতাব", en: "The Book of the Qiblah"),
      10: GeneratedHadithChapterTitle(ar: "كتاب الإمامة", bn: "নামাজে ইমামতির কিতাব", en: "The Book of Leading the Prayer (Al-Imamah)"),
      11: GeneratedHadithChapterTitle(ar: "كتاب الافتتاح", bn: "নামাজ শুরুর কিতাব", en: "The Book of the Commencement of the Prayer"),
      12: GeneratedHadithChapterTitle(ar: "كتاب التطبيق", bn: "আত-তাতবিকের কিতাব", en: "The Book of The At-Tatbiq (Clasping One's Hands Together)"),
      13: GeneratedHadithChapterTitle(ar: "كتاب السهو", bn: "নামাজে ভুলের কিতাব", en: "The Book of Forgetfulness (In Prayer)"),
      14: GeneratedHadithChapterTitle(ar: "كتاب الجمعة", bn: "জুমার কিতাব", en: "The Book of Jumu'ah (Friday Prayer)"),
      15: GeneratedHadithChapterTitle(ar: "كتاب قصر الصلاة بالسفر", bn: "সফরে নামাজ কসর করার কিতাব", en: "The Book of Shortening the Prayer When Traveling"),
      16: GeneratedHadithChapterTitle(ar: "كتاب الكسوف", bn: "গ্রহণের কিতাব", en: "The Book of Eclipses"),
      17: GeneratedHadithChapterTitle(ar: "كتاب الاستسقاء", bn: "বৃষ্টির দোয়ার কিতাব", en: "The Book of Praying for Rain (Al-Istisqa')"),
      18: GeneratedHadithChapterTitle(ar: "كتاب صلاة الخوف", bn: "খুফ নামাজের কিতাব", en: "The Book of the Fear Prayer"),
      19: GeneratedHadithChapterTitle(ar: "كتاب صلاة العيدين", bn: "দুই ঈদের নামাজের কিতাব", en: "The Book of the Prayer for the Two 'Eids"),
      20: GeneratedHadithChapterTitle(ar: "كتاب قيام الليل والتطوعات بالنهار", bn: "তাহাজ্জুদ ও দিনের নফল নামাজের কিতাব", en: "The Book of Qiyam Al-Lail (The Night Prayer) and Voluntary Prayers During the Day"),
      21: GeneratedHadithChapterTitle(ar: "كتاب الجنائز", bn: "জানাজার কিতাব", en: "The Book of Funerals"),
      22: GeneratedHadithChapterTitle(ar: "كتاب الصيام", bn: "রোজার কিতাব", en: "The Book of Fasting"),
      23: GeneratedHadithChapterTitle(ar: "كتاب الزكاة", bn: "যাকাতের কিতাব", en: "The Book of Zakah"),
      24: GeneratedHadithChapterTitle(ar: "كتاب الحج", bn: "হজের কিতাব", en: "The Book of Hajj"),
      25: GeneratedHadithChapterTitle(ar: "كتاب الجهاد", bn: "জিহাদের কিতাব", en: "The Book of Jihad"),
      26: GeneratedHadithChapterTitle(ar: "كتاب النكاح", bn: "বিবাহের কিতাব", en: "The Book of Marriage"),
      27: GeneratedHadithChapterTitle(ar: "كتاب الطلاق", bn: "তালাকের কিতাব", en: "The Book of Divorce"),
      28: GeneratedHadithChapterTitle(ar: "كتاب الخيل والسبق والرماية", bn: "ঘোড়া, দৌড় ও নিক্ষেপের কিতাব", en: "The Book of Horses, Races and Shooting"),
      29: GeneratedHadithChapterTitle(ar: "كتاب الوقف", bn: "ওয়াকফের কিতাব", en: "The Book of Endowments"),
      30: GeneratedHadithChapterTitle(ar: "كتاب الوصية", bn: "ওসিয়তের কিতাব", en: "The Book of Wills"),
      31: GeneratedHadithChapterTitle(ar: "كتاب الهدية", bn: "উপহারের কিতাব", en: "The Book of Presents"),
      32: GeneratedHadithChapterTitle(ar: "كتاب الهبة", bn: "দানের কিতাব", en: "The Book of Gifts"),
      33: GeneratedHadithChapterTitle(ar: "كتاب الرقبى", bn: "আর-রুকবার কিতাব", en: "The Book of ar-Ruqba"),
      34: GeneratedHadithChapterTitle(ar: "كتاب العمرة", bn: "উমরার কিতাব", en: "The Book of 'Umra"),
      35: GeneratedHadithChapterTitle(ar: "كتاب المزارعة", bn: "কৃষির কিতাব", en: "The Book of Agriculture"),
      36: GeneratedHadithChapterTitle(ar: "كتاب معاشرة النساء", bn: "নারীদের সদয় আচরণের কিতাব", en: "The Book of the Kind Treatment of Women"),
      37: GeneratedHadithChapterTitle(ar: "كتاب القتال [تحريم الدم]", bn: "যুদ্ধের কিতাব [রক্তপাতের নিষেধাজ্ঞা]", en: "The Book of Fighting [The Prohibition of Bloodshed]"),
      38: GeneratedHadithChapterTitle(ar: "كتاب الفيء", bn: "আল-ফাই বণ্টনের কিতাব", en: "The Book of Distribution of Al-Fay'"),
      39: GeneratedHadithChapterTitle(ar: "كتاب البيعة", bn: "বাইয়ার কিতাব", en: "The Book of al-Bay'ah"),
      40: GeneratedHadithChapterTitle(ar: "كتاب العقيقة", bn: "আকীকার কিতাব", en: "The Book of al-'Aqiqah"),
      41: GeneratedHadithChapterTitle(ar: "كتاب الفرع والعتيرة", bn: "আল-ফারা ও আল-আতিরার কিতাব", en: "The Book of al-Fara' and al-'Atirah"),
      42: GeneratedHadithChapterTitle(ar: "كتاب الصيد والذبائح", bn: "শিকার ও জবাইয়ের কিতাব", en: "The Book of Hunting and Slaughtering"),
      43: GeneratedHadithChapterTitle(ar: "كتاب الضحايا", bn: "আদ-দাহায়া (কুরবানি) এর কিতাব", en: "The Book of ad-Dahaya (Sacrifices)"),
      44: GeneratedHadithChapterTitle(ar: "كتاب البيوع", bn: "আর্থিক লেনদেনের কিতাব", en: "The Book of Financial Transactions"),
      45: GeneratedHadithChapterTitle(ar: "كتاب القسامة والقصاص والديات", bn: "শপথ (কাসামাহ), প্রতিশোধ ও দিয়াতের কিতাব", en: "The Book of Oaths (qasamah), Retaliation and Blood Money"),
      46: GeneratedHadithChapterTitle(ar: "كتاب قطع السارق", bn: "চোরের হাত কাটার কিতাব", en: "The Book of Cutting off the Hand of the Thief"),
      47: GeneratedHadithChapterTitle(ar: "كتاب الإيمان وأشراطه", bn: "ঈমান ও তার লক্ষণের কিতাব", en: "The Book Of Faith and its Signs"),
      48: GeneratedHadithChapterTitle(ar: "كتاب الزينة", bn: "সাজসজ্জার কিতাব", en: "The Book of Adornment"),
      49: GeneratedHadithChapterTitle(ar: "كتاب آداب القضاة", bn: "বিচারকদের আদবের কিতাব", en: "The Book of the Etiquette of Judges"),
      50: GeneratedHadithChapterTitle(ar: "كتاب الاستعاذة", bn: "আল্লাহর আশ্রয় প্রার্থনার কিতাব", en: "The Book of Seeking Refuge with Allah"),
      51: GeneratedHadithChapterTitle(ar: "كتاب الأشربة", bn: "পানীয়ের কিতাব", en: "The Book of Drinks"),
    },
    'ibnmajah': {
      0: GeneratedHadithChapterTitle(ar: "كتاب المقدمة", bn: "সুন্নাহর কিতাব", en: "The Book of the Sunnah"),
      1: GeneratedHadithChapterTitle(ar: "كتاب الطهارة وسننها", bn: "পবিত্রতা ও তার সুন্নাহর কিতাব", en: "The Book of Purification and its Sunnah"),
      2: GeneratedHadithChapterTitle(ar: "كتاب الصلاة", bn: "নামাজের কিতাব", en: "The Book of the Prayer"),
      3: GeneratedHadithChapterTitle(ar: "كتاب الأذان وسننه", bn: "আজান ও তার সুন্নাহর কিতাব", en: "The Book of the Adhan and the Sunnah Regarding It"),
      4: GeneratedHadithChapterTitle(ar: "كتاب المساجد والجماعات", bn: "মসজিদ ও জামাআতের কিতাব", en: "The Book On The Mosques And The Congregations"),
      5: GeneratedHadithChapterTitle(ar: "كتاب إقامة الصلاة وسننها", bn: "নামাজ প্রতিষ্ঠা ও তার সুন্নাহর কিতাব", en: "Establishing the Prayer and the Sunnah Regarding Them"),
      6: GeneratedHadithChapterTitle(ar: "كتاب الجنائز", bn: "জানাজা সংক্রান্ত অধ্যায়", en: "Chapters Regarding Funerals"),
      7: GeneratedHadithChapterTitle(ar: "كتاب الصيام", bn: "রোজা", en: "Fasting"),
      8: GeneratedHadithChapterTitle(ar: "كتاب الزكاة", bn: "যাকাত সংক্রান্ত অধ্যায়", en: "The Chapters Regarding Zakat"),
      9: GeneratedHadithChapterTitle(ar: "كتاب النكاح", bn: "বিবাহ সংক্রান্ত অধ্যায়", en: "The Chapters on Marriage"),
      10: GeneratedHadithChapterTitle(ar: "كتاب الطلاق", bn: "তালাক সংক্রান্ত অধ্যায়", en: "The Chapters on Divorce"),
      15: GeneratedHadithChapterTitle(ar: "كتاب الصدقة", bn: "দান সংক্রান্ত অধ্যায়", en: "The Chapters on Charity"),
      19: GeneratedHadithChapterTitle(ar: "كتاب العتق", bn: "দাস মুক্তি সংক্রান্ত অধ্যায়", en: "The Chapters on Manumission (of Slaves)"),
      20: GeneratedHadithChapterTitle(ar: "كتاب الحدود", bn: "হদ সংক্রান্ত অধ্যায়", en: "The Chapters on Legal Punishments"),
      21: GeneratedHadithChapterTitle(ar: "كتاب الديات", bn: "দিয়াত সংক্রান্ত অধ্যায়", en: "The Chapters on Blood Money"),
      22: GeneratedHadithChapterTitle(ar: "كتاب الوصايا", bn: "ওসিয়ত সংক্রান্ত অধ্যায়", en: "The Chapters on Wills"),
      23: GeneratedHadithChapterTitle(ar: "كتاب الفرائض", bn: "উত্তরাধিকারের অংশ সংক্রান্ত অধ্যায়", en: "Chapters on Shares of Inheritance"),
      24: GeneratedHadithChapterTitle(ar: "كتاب الجهاد", bn: "জিহাদ সংক্রান্ত অধ্যায়", en: "The Chapters on Jihad"),
      25: GeneratedHadithChapterTitle(ar: "كتاب المناسك", bn: "হজের আনুষ্ঠানিকতা সংক্রান্ত অধ্যায়", en: "Chapters on Hajj Rituals"),
      26: GeneratedHadithChapterTitle(ar: "كتاب الأضاحي", bn: "কুরবানি সংক্রান্ত অধ্যায়", en: "Chapters on Sacrifices"),
      27: GeneratedHadithChapterTitle(ar: "كتاب الذبائح", bn: "জবাই সংক্রান্ত অধ্যায়", en: "Chapters on Slaughtering"),
      28: GeneratedHadithChapterTitle(ar: "كتاب الصيد", bn: "শিকার সংক্রান্ত অধ্যায়", en: "Chapters on Hunting"),
      29: GeneratedHadithChapterTitle(ar: "كتاب الأطعمة", bn: "খাদ্য সংক্রান্ত অধ্যায়", en: "Chapters on Food"),
      30: GeneratedHadithChapterTitle(ar: "كتاب الأشربة", bn: "পানীয় সংক্রান্ত অধ্যায়", en: "Chapters on Drinks"),
      31: GeneratedHadithChapterTitle(ar: "كتاب الطب", bn: "চিকিৎসা সংক্রান্ত অধ্যায়", en: "Chapters on Medicine"),
      32: GeneratedHadithChapterTitle(ar: "كتاب اللباس", bn: "পোশাক সংক্রান্ত অধ্যায়", en: "Chapters on Dress"),
      33: GeneratedHadithChapterTitle(ar: "كتاب الأدب", bn: "শিষ্টাচার", en: "Etiquette"),
      34: GeneratedHadithChapterTitle(ar: "كتاب الدعاء", bn: "দোয়া", en: "Supplication"),
      35: GeneratedHadithChapterTitle(ar: "كتاب تعبير الرؤيا", bn: "স্বপ্নের ব্যাখ্যা", en: "Interpretation of Dreams"),
      36: GeneratedHadithChapterTitle(ar: "كتاب الفتن", bn: "ফিতনা", en: "Tribulations"),
      37: GeneratedHadithChapterTitle(ar: "كتاب الزهد", bn: "জুহদ", en: "Zuhd"),
    },
    'malik': {
      0: GeneratedHadithChapterTitle(ar: "غير مصنف", bn: "অশ্রেণীবদ্ধ", en: "Uncategorized"),
      1: GeneratedHadithChapterTitle(ar: "كتاب وقت الصلاة", bn: "নামাজের সময়", en: "The Times of Prayer"),
      2: GeneratedHadithChapterTitle(ar: "كتاب الطهارة", bn: "পবিত্রতা", en: "Purity"),
      3: GeneratedHadithChapterTitle(ar: "كتاب الصلاة", bn: "নামাজ", en: "Prayer"),
      4: GeneratedHadithChapterTitle(ar: "كتاب السهو", bn: "নামাজে ভুল", en: "Forgetfulness in Prayer"),
      5: GeneratedHadithChapterTitle(ar: "كتاب الجمعة", bn: "জুমা", en: "Jumu'a"),
      6: GeneratedHadithChapterTitle(ar: "كتاب صلاة رمضان", bn: "রমজানে নামাজ", en: "Prayer in Ramadan"),
      7: GeneratedHadithChapterTitle(ar: "كتاب التهجد", bn: "তাহাজ্জুদ", en: "Tahajjud"),
      8: GeneratedHadithChapterTitle(ar: "كتاب صلاة الجماعة", bn: "জামাআতে নামাজ", en: "Prayer in Congregation"),
      9: GeneratedHadithChapterTitle(ar: "كتاب قصر الصلاة", bn: "নামাজ কসর", en: "Shortening the Prayer"),
      10: GeneratedHadithChapterTitle(ar: "كتاب العيدين", bn: "দুই ঈদ", en: "The Two 'Ids"),
      11: GeneratedHadithChapterTitle(ar: "كتاب صلاة الخوف", bn: "খুফ নামাজ", en: "The Fear Prayer"),
      12: GeneratedHadithChapterTitle(ar: "كتاب الكسوف", bn: "গ্রহণের নামাজ", en: "The Eclipse Prayer"),
      13: GeneratedHadithChapterTitle(ar: "كتاب الاستسقاء", bn: "বৃষ্টির দোয়া", en: "Asking for Rain"),
      14: GeneratedHadithChapterTitle(ar: "كتاب القبلة", bn: "কিবলা", en: "The Qibla"),
      15: GeneratedHadithChapterTitle(ar: "كتاب القرآن", bn: "কুরআন", en: "The Qur'an"),
      16: GeneratedHadithChapterTitle(ar: "كتاب الجنائز", bn: "দাফন", en: "Burials"),
      17: GeneratedHadithChapterTitle(ar: "كتاب الزكاة", bn: "যাকাত", en: "Zakat"),
      18: GeneratedHadithChapterTitle(ar: "كتاب الصيام", bn: "রোজা", en: "Fasting"),
      19: GeneratedHadithChapterTitle(ar: "كتاب الاعتكاف", bn: "রমজানে ইতিকাফ", en: "I'tikaf in Ramadan"),
      20: GeneratedHadithChapterTitle(ar: "كتاب الحج", bn: "হজ", en: "Hajj"),
      21: GeneratedHadithChapterTitle(ar: "كتاب الجهاد", bn: "জিহাদ", en: "Jihad"),
      22: GeneratedHadithChapterTitle(ar: "كتاب الأيمان والنذور", bn: "মানত ও শপথ", en: "Vows and Oaths"),
      23: GeneratedHadithChapterTitle(ar: "كتاب الضحايا", bn: "কুরবানির পশু", en: "Sacrificial Animals"),
      24: GeneratedHadithChapterTitle(ar: "كتاب الذبائح", bn: "পশু জবাই", en: "Slaughtering Animals"),
      25: GeneratedHadithChapterTitle(ar: "كتاب الصيد", bn: "শিকার", en: "Game"),
      26: GeneratedHadithChapterTitle(ar: "كتاب العقيقة", bn: "আকীকা", en: "The 'Aqiqa"),
      27: GeneratedHadithChapterTitle(ar: "كتاب الفرائض", bn: "ফারায়িদ", en: "Fara'id"),
      28: GeneratedHadithChapterTitle(ar: "كتاب النكاح", bn: "বিবাহ", en: "Marriage"),
      29: GeneratedHadithChapterTitle(ar: "كتاب الطلاق", bn: "তালাক", en: "Divorce"),
      30: GeneratedHadithChapterTitle(ar: "كتاب الرضاع", bn: "দুধ পান", en: "Suckling"),
      31: GeneratedHadithChapterTitle(ar: "كتاب البيوع", bn: "ব্যবসায়িক লেনদেন", en: "Business Transactions"),
      32: GeneratedHadithChapterTitle(ar: "كتاب القراض", bn: "কিরাদ", en: "Qirad"),
      33: GeneratedHadithChapterTitle(ar: "كتاب المساقاة", bn: "ভাগচাষ", en: "Sharecropping"),
      34: GeneratedHadithChapterTitle(ar: "كتاب كراء الأرض", bn: "জমি ভাড়া", en: "Renting Land"),
      35: GeneratedHadithChapterTitle(ar: "كتاب الشفعة", bn: "সম্পত্তিতে শুফা", en: "Pre-emption in Property"),
      36: GeneratedHadithChapterTitle(ar: "كتاب الأحكام", bn: "বিচার", en: "Judgements"),
      37: GeneratedHadithChapterTitle(ar: "كتاب الوصية", bn: "ওসিয়ত ও ওয়াসিয়্যাত", en: "Wills and Testaments"),
      38: GeneratedHadithChapterTitle(ar: "كتاب العتق والولاء", bn: "মুক্তি ও ওয়ালা", en: "Setting Free and Wala'"),
      39: GeneratedHadithChapterTitle(ar: "كتاب المكاتب", bn: "মুকাতাব", en: "The Mukatab"),
      40: GeneratedHadithChapterTitle(ar: "كتاب المدبر", bn: "মুদাব্বার", en: "The Mudabbar"),
      41: GeneratedHadithChapterTitle(ar: "كتاب الحدود", bn: "হুদুদ", en: "Hudud"),
      42: GeneratedHadithChapterTitle(ar: "كتاب الأشربة", bn: "পানীয়", en: "Drinks"),
      43: GeneratedHadithChapterTitle(ar: "كتاب الديات", bn: "দিয়াত", en: "Blood-Money"),
      44: GeneratedHadithChapterTitle(ar: "كتاب القسامة", bn: "কাসামার শপথ", en: "The Oath of Qasama"),
      45: GeneratedHadithChapterTitle(ar: "كتاب المدينة", bn: "মদিনা", en: "Madina"),
      46: GeneratedHadithChapterTitle(ar: "كتاب القدر", bn: "তাকদীর", en: "The Decree"),
      47: GeneratedHadithChapterTitle(ar: "كتاب حسن الخلق", bn: "সদাচার", en: "Good Character"),
      48: GeneratedHadithChapterTitle(ar: "كتاب اللباس", bn: "পোশাক", en: "Dress"),
      49: GeneratedHadithChapterTitle(ar: "كتاب صفة النبى صلى الله عليه وسلم", bn: "নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লামের বর্ণনা সম্পর্কিত অধ্যায়", en: "The book about the description of the Prophet, may God bless him and grant him peace"),
      56: GeneratedHadithChapterTitle(ar: "كتاب الكلام", bn: "বক্তৃতা", en: "Speech"),
      57: GeneratedHadithChapterTitle(ar: "كتاب النار", bn: "জাহান্নাম", en: "Jahannam"),
      58: GeneratedHadithChapterTitle(ar: "كتاب الصدقة", bn: "সাদাকা", en: "Sadaqa"),
      59: GeneratedHadithChapterTitle(ar: "كتاب العلم", bn: "জ্ঞান", en: "Knowledge"),
      60: GeneratedHadithChapterTitle(ar: "كتاب دعوة المظلوم", bn: "নির্যাতিতের দোয়া", en: "The Supplication of the Unjustly Wronged"),
      61: GeneratedHadithChapterTitle(ar: "كتاب أسماء النبي صلى الله عليه وسلم", bn: "নবীর নাম", en: "The Names of the Prophet, may Allah Bless Him and Grant Him Peace"),
    },
  };
}

class GeneratedHadithChapterTitle {
  final String ar;
  final String bn;
  final String en;

  const GeneratedHadithChapterTitle({
    required this.ar,
    required this.bn,
    required this.en,
  });
}
