// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATf2FvoymD4uEH_WCDiZ92KoNANYZ5WbE',
    appId: '1:220451879730:web:ef28e431c4378c4e08b52b',
    messagingSenderId: '220451879730',
    projectId: 'nurverse',
    authDomain: 'nurverse.firebaseapp.com',
    storageBucket: 'nurverse.firebasestorage.app',
    measurementId: 'G-XCF5EXT8JT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwLk6hW0Uj9h4f563zmr3waCeiCOTePzg',
    appId: '1:220451879730:android:2731320a9193999308b52b',
    messagingSenderId: '220451879730',
    projectId: 'nurverse',
    storageBucket: 'nurverse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCIzg1-QzWe1Sb0uluz_acYhtRXkXCT7E',
    appId: '1:220451879730:ios:742d5fc629e5a6fd08b52b',
    messagingSenderId: '220451879730',
    projectId: 'nurverse',
    storageBucket: 'nurverse.firebasestorage.app',
    iosBundleId: 'com.example.nurverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCIzg1-QzWe1Sb0uluz_acYhtRXkXCT7E',
    appId: '1:220451879730:ios:742d5fc629e5a6fd08b52b',
    messagingSenderId: '220451879730',
    projectId: 'nurverse',
    storageBucket: 'nurverse.firebasestorage.app',
    iosBundleId: 'com.example.nurverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATf2FvoymD4uEH_WCDiZ92KoNANYZ5WbE',
    appId: '1:220451879730:web:697019b18ac96d1308b52b',
    messagingSenderId: '220451879730',
    projectId: 'nurverse',
    authDomain: 'nurverse.firebaseapp.com',
    storageBucket: 'nurverse.firebasestorage.app',
    measurementId: 'G-NX9K7WNR1E',
  );
}
