name: Settings repair
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  repair:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
      - uses: actions/checkout@v4
      - run: echo repair
